module.exports = {
  AzureWebJobsStorage: 'AzureWebJobsStorage',
  CONTACT_LIST_BATCHES_CONTAINER: 'CONTACT_LIST_BATCHES_CONTAINER',
  CONTACT_LIST_BATCHES_QUEUE: 'CONTACT_LIST_BATCHES_QUEUE',
  CONTACT_LIST_CONTAINER: 'CONTACT_LIST_CONTAINER',
  INITIAL_MESSAGE_VISIBILITY: 2,
  NOTIFY_CLIENT_API_KEY: 'NOTIFY_CLIENT_API_KEY',
  NOTIFY_TEMPLATE_ID: 'NOTIFY_TEMPLATE_ID'
}
