module.exports = {
  AzureWebJobsStorage: 'AzureWebJobsStorage',
  CONTACT_LIST_BATCHES_CONTAINER: 'CONTACT_LIST_BATCHES_CONTAINER',
  CONTACT_LIST_BATCHES_QUEUE: 'CONTACT_LIST_BATCHES_QUEUE',
  CONTACT_LIST_CONTAINER: 'CONTACT_LIST_CONTAINER',
  INITIAL_MESSAGE_VISIBILITY: 2,
  NOTIFICATIONS_FAILED_TO_SEND_QUEUE: 'NOTIFICATIONS_TO_SEND_QUEUE',
  NOTIFICATIONS_FAILED_TO_SEND_RATE_LIMIT_QUEUE: 'NOTIFICATIONS_FAILED_TO_SEND_RATE_LIMIT_QUEUE',
  NOTIFY_CLIENT_API_KEY: 'NOTIFY_CLIENT_API_KEY',
  NOTIFY_TEMPLATE_ID: 'NOTIFY_TEMPLATE_ID'
}
