const envVars = require('./test/testEnvVars')

process.env.AzureWebJobsStorage = envVars.AzureWebJobsStorage
process.env.CONTACT_LIST_BATCHES_CONTAINER = envVars.CONTACT_LIST_BATCHES_CONTAINER
process.env.CONTACT_LIST_CONTAINER = envVars.CONTACT_LIST_CONTAINER
process.env.CONTACT_LIST_BATCHES_QUEUE = envVars.CONTACT_LIST_BATCHES_QUEUE
process.env.INITIAL_MESSAGE_VISIBILITY = envVars.INITIAL_MESSAGE_VISIBILITY
process.env.NOTIFY_CLIENT_API_KEY = envVars.NOTIFY_CLIENT_API_KEY
process.env.NOTIFY_TEMPLATE_ID = envVars.NOTIFY_TEMPLATE_ID
process.env.NOTIFICATIONS_FAILED_TO_SEND_QUEUE = envVars.NOTIFICATIONS_FAILED_TO_SEND_QUEUE
process.env.NOTIFICATIONS_FAILED_TO_SEND_RATE_LIMIT_QUEUE = envVars.NOTIFICATIONS_FAILED_TO_SEND_RATE_LIMIT_QUEUE
